### ISSUE TITLE
"Last Tripped Time" for G3 Motion Detection sensor is in GMT

### ISSUE THREAD

**Issue by andrewwong2000** [briis/unifiprotect#164] opened 2020-12-23 00:22 UTC
Hi Bjarne,

Thanks for your work to produce this integration! I've just installed Unifi Protect via HACS and it seems to be working fine.

I have one question about the sensor state, which is appearing in GMT.

My Unifi Protect/CSKG2+ are setup with GMT+8 and my HomeAssistant is also correctly showing the local TZ and time.

Any suggestions on how to get this to display correctly ?
<img width="327" alt="Screen Shot 2020-12-23 at 8 21 38 am" src="https://user-images.githubusercontent.com/20747889/102945172-f69c9580-44f7-11eb-9e1b-4c3dff5a3a22.png">
<img width="320" alt="Screen Shot 2020-12-23 at 8 21 31 am" src="https://user-images.githubusercontent.com/20747889/102945182-ff8d6700-44f7-11eb-818f-2e071c552ff7.png">

**Comment by briis** [comment] 2020-12-23 06:11
Mine work fine, and I am GMT+1.
Basically date & time can come from 3 sources:
- The Computer you run Home Assistant on
- Home Assistant itself
- The UnFi Protect Server
Are you absolutely sure that the Timezone is set correctly on your CK+? We don't do anything with the datetime value coming from the UFP, we just display it - so my guess is that the wrong datetime comes from there.

**Comment by andrewwong2000** [comment] 2020-12-23 06:36
Thanks for replying..

I have checked System TZdata, Home Assistant, the CSK+ and Unifi Protect:

<img width="567" alt="Screen Shot 2020-12-23 at 2 13 51 pm" src="https://user-images.githubusercontent.com/20747889/102966941-e1415e80-452b-11eb-92c9-d354fd20bf8a.png">
<img width="533" alt="Screen Shot 2020-12-23 at 2 13 36 pm" src="https://user-images.githubusercontent.com/20747889/102966950-e43c4f00-452b-11eb-9e77-251d38394ec1.png">
<img width="548" alt="Screen Shot 2020-12-23 at 2 34 31 pm" src="https://user-images.githubusercontent.com/20747889/102967007-03d3778
<img width="414" alt="Screen Shot 2020-12-23 at 2 36 02 pm" src="https://user-images.githubusercontent.com/20747889/102967117-367d7000-452c-11eb-8991-9a851c617982.png">
0-452c-11eb-97e6-cf393f9bda89.png">

**Comment by briis** [comment] 2020-12-23 06:38
That is strange. I will try and set my test system to this, and see what I get.

**Comment by briis** [comment] 2020-12-23 06:53
I can confirm that I also get GMT time on my CK+ with FW 2.0.24 and UniFi Protect 1.17.0-Beta9.
The issue seems to be isolated to the CK+ as I don't have the issue on my UDMP. I will dig some more in to the raw data, and see if this is solvable in the Integration or you need to do the timezone conversion in a template.

**Comment by briis** [comment] 2020-12-23 12:08
I did a lot more testing on this, and found that is has nothing to do with this Integration or what UniFi Protect server you are running. It all depends on the server that Home Assistant is running on. If I add my test CK+ to my Production Home Assistant, the times are displayed correctly and so are the times from my UDMP. If I add the same CK+ and UDMP to my development machine, I get the GMT times instead.

What settings exactly makes this difference, I don't know at this point, but now you know where to look. I will keep digging and post here if I find the cause, and please do the same if you find it.

What is your HA environment? Docker, VM, HassIO??

**Comment by briis** [comment] 2020-12-23 12:57
New Finding: If you run in a Docker Environment, make sure that the TZ parameter is set to Australia/Perth on the docker container - I found that when this is not set, or set wrongly, that will influence the time displayed.

**Comment by andrewwong2000** [comment] 2020-12-23 15:20
Thanks !! There was list to work through.  Will try this out tomorrow :)

**Comment by andrewwong2000** [comment] 2020-12-24 02:49
Hi Bjarne,

Thanks for helping to troubleshoot.

I run HA under Docker.. I will check to see if there are docker specific TZ settings.

It’s weird that everything else is reporting time in local time. 

Might not troubleshoot this till later.. I just tried OZW and killed my Z-Wave setup :)

Thanks,

Andrew

**Comment by briis** [comment] 2020-12-24 06:06
Fu.. I know the feeling when you try something, and then all goes BUUUM. Hope you get it restored.

I agree it is strange, and TZ might not bee the reason, but it has until now been the only thing I found that differs between my production environment and test environments. And I know that changing this, changes the times displayed.

We have not changed anything in the code that delivers this datetime for month, so if it was a general issue, I would assume a other people had noticed a long time ago.

**Comment by briis** [comment] 2021-02-01 08:35
Did you get your OZW fixed? Are you still having the issue? If not, I will close this issue.

**Comment by andrewwong2000** [comment] 2021-02-01 08:58
HI Bjarne

Thanks for following up !

Yes adding the TZ to Docker fixed the issue :)

Thanks again for your dedication to the development.

Regards,

Andrew

**Comment by briis** [comment] 2021-02-01 08:59
Beautiful and thanks. I will close this now.

**Closed by briis** 2021-02-01 08:59 UTC
Labels: question
