### ISSUE TITLE
Massive delay in video feed

### ISSUE THREAD

**Issue by NVader2000** [briis/unifiprotect#175] opened 2021-01-11 00:37 UTC
Got this work, I guess. However, the video is far from real time. Around a 20 second delay from reality. Also, the title only show the camera icon and I must click on it to get video feed.

**Comment by NVader2000** [comment] 2021-01-11 00:48
Ok figured out the video feed tile issue, but still have a 20 second delay in the video. Please advise.

**Comment by NVader2000** [comment] 2021-01-11 00:51
Also, not sure why the RTSP is needed for and/or where it gets added.

**Comment by briis** [comment] 2021-01-11 05:47
There has been some discussions on this topic in the Home Assistant Community Forum. There seems to be some changes in the `stream` component that has prevented the G3 series of cameras to autostart the feed, where as the G4 series still work. So if you have G3 series, that is why you have to click to get the live stream. 

The only live stream that Unifi Protect serves outside the Protect App is the RTSP stream, so this is why this is used. If you read the documentation in the README.md file in this Repository you will see how to enable it.

The delay is a well known issue, that seems to be caused by the way the stream component in HA works, and has also been discussed numerous times. There is currently nothing I can do about that.

**Comment by NVader2000** [comment] 2021-01-11 16:16
I already have the RTSP enabled. So, is there somewhere I need to copy that information inside the UniFi Protect Integration or does it just starts working?

**Comment by briis** [comment] 2021-01-11 19:08
If RTSP is enabled for the Camera, it will automatically loaded when Home Assistant starts.
You should also add `stream:` to your `configuration.yaml` file, as this is needed for streaming to work

**Comment by scpotter** [comment] 2021-01-15 23:10
> You should also add `stream:` to your `configuration.yaml` file, as this is needed for streaming to work

I just set the integration up (awesome BTW) and didn’t see this in the documentation, maybe it should be under Configuration?

**Comment by briis** [comment] 2021-01-16 05:53
Good point with stream in the documentation. I will do that.
Please close the issue, if think it is closed.

**Comment by briis** [comment] 2021-02-01 08:06
I have added this to the Documentation, so I will close this now.

**Closed by briis** 2021-02-01 08:06 UTC
