### ISSUE TITLE
G4 Doorbell transitioning between offline and online status yields ring event in Homekit.

### ISSUE THREAD

**Issue by crkochan** [briis/unifiprotect#150] opened 2020-12-01 20:02 UTC
I've had the integration setup for a while now, bringing all of my Protect cameras (total of four at the moment) into Home Assistant. I've also setup a Homekit bridge integration in HA for the camera domain to expose them to Homekit. All of this has been working fine for several months at minimum.

Recently though, what's begun to happen is that anytime my G4 Doorbell disconnects from wifi for whatever reason, Homekit reacts as though someone has rung the doorbell. The event will happen again when it reconnects as well. I first noticed this happening on or about November 21st. 

These disconnects for the doorbell do happen periodically, typically lasting a couple minutes before it pops back online. In fact, prior to 11/21, there were two other disconnect events earlier in the month, where I don't recall having gotten a ring notification from Homekit. I haven't tuned my notifications, so a legit button press usually results in notifications from the iOS Protect app, Homekit, and chime sounds from my Homepods all at the same time, meaning the events are memorable.

I can reproduce the issue consistently by using the reconnect function in Unifi Network to drop the doorbell off of wifi and make it reconnect again, or by rebooting the unit in Protect.

I'm not sure if this is something to do with the integration itself, or the Homekit bridge integration in HA, or a weird edge case caused by a combination of both. I figured I'd start here though. 

Home Assistant version: 0.118.4
Unifi Protect Integration version: 0.6.5
Unifi Protect controller version: 1.15.0
Unifi Protect hardware: UNVR
UNVR firmware version: 1.3.15

**Comment by Dragonpark** [comment] 2020-12-01 20:41
I recently saw the same behavior last night as well, which happened to be at around 2am. I logged into the camera and grabbed the support bundle, but it doesn't seem to show anything obvious. It is worth noting that my doorbell does not get the best wifi connection due to some brick, but it is normally good enough, however the logs are still filled with poor signal messages. Additionally, Protect showed the camera disconnecting/reconnecting for about an hour and a half (likely due to the poor signal reception). This obviously isn't the fault of the integration, but should be handled a bit better if the disconnects are the cause.

I'm not really sure if this is a red herring or what, but I just so happened to update the integration to 0.6.5. Unfortunately, I do not recall exactly what version it was at prior, but may have been something like 0.6.2 or 0.6.3.

Home Assistant version: 0.118.4
Unifi Protect Integration version: 0.6.5
Unifi Protect controller version: 1.15.0
Unifi Protect hardware: UDM-Pro
UNVR firmware version: 1.8.0

**Comment by crkochan** [comment] 2020-12-01 21:47
I did some testing on prior versions. Same methodology as before, drop the doorbell from wifi via reconnect from Unifi Network controller.

Integration version 0.6.4: Ring event on disconnect/reconnect
Integration version 0.6.3: No ring event on disconnect/reconnect

**Comment by crkochan** [comment] 2020-12-01 21:54
Just to cover more bases, I also updated to 0.6.6-beta-1 which also produces a ring event like the current stable.

**Comment by crkochan** [comment] 2020-12-01 22:19
I turned on debug logging for custom components, and ran some reconnects on v0.6.5 to see if I got anything interesting.

This was the block of logs that showed up on the console during the first reconnect.
```
2020-12-01 14:06:53 DEBUG (MainThread) [custom_components.unifiprotect.binary_sensor] RING False: Doorbell Front Door
2020-12-01 14:06:53 DEBUG (MainThread) [custom_components.unifiprotect.binary_sensor] RING True: Doorbell Front Door
2020-12-01 14:06:55 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsp://10.0.15.25:7447/jjjcqs0iDAL1yBZF
2020-12-01 14:06:56 DEBUG (MainThread) [custom_components.unifiprotect.binary_sensor] RING False: Doorbell Front Door
2020-12-01 14:06:56 DEBUG (MainThread) [custom_components.unifiprotect.binary_sensor] RING True: Doorbell Front Door
2020-12-01 14:06:58 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Error Code: 500 - Error Status: Internal Server Error
```

That RTSP URL is the proper one for my doorbell.

I ran several more reconnects after that, and timestamps aside, they all yielded the same block.
```
2020-12-01 14:11:50 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream: 
2020-12-01 14:11:51 DEBUG (MainThread) [custom_components.unifiprotect.binary_sensor] RING False: Doorbell Front Door
2020-12-01 14:11:51 DEBUG (MainThread) [custom_components.unifiprotect.binary_sensor] RING True: Doorbell Front Door
2020-12-01 14:11:53 DEBUG (MainThread) [custom_components.unifiprotect.binary_sensor] RING False: Doorbell Front Door
2020-12-01 14:11:53 DEBUG (MainThread) [custom_components.unifiprotect.binary_sensor] RING True: Doorbell Front Door
2020-12-01 14:11:56 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Error Code: 500 - Error Status: Internal Server Error
```

The only difference being that this time the stream worker complains about an error demuxing versus the error opening yielded in the first block.

Aside from that, every sixty seconds I get a message about the ring binary sensor in the logs.
```
2020-12-01 14:13:16 DEBUG (MainThread) [custom_components.unifiprotect.binary_sensor] RING False: Doorbell Front Door
```

**Comment by briis** [comment] 2020-12-02 06:07
I can confirm that I can replicate this.

**Comment by briis** [comment] 2020-12-02 07:33
It's a bit tricky to catch this, but I might have a potential solution.
With the 0.6.6-beta-1 installed, could you try and edit the `manifest.json` file in the `custom_components/unifiprotect` directory, and change to *pyunifiprotect==0.24.7* and then restart HA, and try and force the reconnect.

**Comment by crkochan** [comment] 2020-12-02 08:13
I did as instructed and tested. No ringing on disconnect. We still get `RING False: Doorbell Front Door` events in the debug logs, but no `RING True`.

Looks like your add of `EVENT_DISCONNECT` to unifi_data.py did the trick.

**Comment by briis** [comment] 2020-12-02 08:30
@crkochan  Perfect. I had the same experience. The `RING False: Doorbell Front Door` is on purpose, and you know this will disappear if you turn off the debugging for the Integration again. Also the `Error opening stream..` message will still be there, as the camera disconnects, so we cannot read the stream.

@Dragonpark Would be great if you also had the chance to test this, just to make sure before I release it.

**Comment by crkochan** [comment] 2020-12-02 08:34
Ya, that all tracks. I never keep the debug logging on outside of troubleshooting. The community average sensor is quite a firehose of output otherwise.

**Comment by briis** [comment] 2020-12-02 15:00
By coincidence I had to update my main switch today, and when that was restarting I got the error again, even with the 0.24.7 fix applied. So I made an additional check for event_type. If any you are going to test, please use 0.24.8 for the version number of pyunifiprotect. (instead of what I wrote above)
With this release I cannot provoke the error anymore, so I believe it is fixed.

**Comment by crkochan** [comment] 2020-12-02 19:45
I haven't been able to reproduce on 0.24.7, but reboots and reconnects may not be enough to yield a provision event.

In the mean time, as far as I'm concerned, the issue is resolved. I think I prefer to remain on 0.6.3 until a non-beta release with the changes rolls out. I'm not planning on running the beta Protect controller, so the feature adds of the prior releases since then don't really bring anything new to the table for me just yet.

Rather than get off topic on this issue, I [commented](https://github.com/briis/pyunifiprotect/commit/33c60aa866a29d4822c672c519cd7bd0a12f5a6e) on your latest commit to pyunifiprotect. Just curious about the reasoning behind the event handling logic.

**Comment by briis** [comment] 2020-12-02 19:52
Thanks for testing. And yes, it might be enough to just test for `ring`, instead of all the things that it should not be.
But it helped me to figure out where the error occurred.

**Comment by briis** [comment] 2020-12-02 20:16
Version 0.6.6 is now released, which fixes this issue (amongst other things). So if you agree, please close this. Thanks for reporting and helping to test.

**Closed** 2020-12-02 21:41 UTC
Labels: bug
