### ISSUE TITLE
camera requesting width and height

### ISSUE THREAD

**Issue by jazbraz** [briis/unifiprotect#283] opened 2021-08-28 16:46 UTC
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:465
Integration: Kamera (documentation, issues)
First occurred: 0:02:44 (1 occurrences)
Last logged: 0:02:44

The camera entity camera.biorum does not support requesting width and height, please open an issue with the integration author

**Comment by bdraco** [comment] 2021-08-28 16:51
This is a dupe of https://github.com/briis/unifiprotect/issues/282

**Closed by bdraco** 2021-08-28 16:51 UTC
