### ISSUE TITLE
Error Code: 500 - Error Status: Internal Server Error

### ISSUE THREAD

**Issue by coomacheek** [briis/unifiprotect#99] opened 2020-08-16 15:06 UTC
Following error message started showing up recently in my logs.  It may have started after the UNVR update to 1.3.15, but can't say for certain.  On the surface, everything seems to be working - camera feeds, events, etc...

I'm running the following versions:
- Protect 1.14.11
- UNVR 1.3.15
- HA 0.114.1
- HassOS 4.12

Is this a benign message?

```
Log Details (WARNING)
Logger: pyunifiprotect.unifi_protect_server
Source: /usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py:507
First occurred: August 15, 2020, 8:35:38 PM (12 occurrences)
Last logged: 9:14:03 AM

Error Code: 500 - Error Status: Internal Server Error
```

**Comment by briis** [comment] 2020-08-17 06:05
The 5xx errors are the status codes returned by the server when the server encounters an unexpected condition which prevented it from fulfilling the request from a client, and unfortunately I cannot reproduce this on any of my systems. I run an UDMP so also UnifiOS. 

How often do you see this message?

**Comment by coomacheek** [comment] 2020-08-17 11:27
33 times since my last restart of HA which was 17 hours ago.

**Comment by briis** [comment] 2020-08-24 05:24
Thanks for the reproduction steps - I will try and reproduce it here, and see if I can catch the error.

**Comment by briis** [comment] 2020-10-26 19:43
During development of the next release we did some intensive tests and it turns out there is most likely a Bug in Unifi Protect that causes this. The error handling has now been improved, that should handle this better.
I will close this issue now, as there is currently not more I can do.

**Closed by briis** 2020-10-26 19:43 UTC
