### ISSUE TITLE
Motion Sensor entity does not survive Device becoming unavailable

### ISSUE THREAD

**Issue by jb123567** [briis/unifiprotect#317] opened 2021-10-27 02:45 UTC
If a camera becomes unavailable, for example due to a firmware update or a network update the motion sensor entity will no longer update and HA needs to be restarted.

**Comment by AngellusMortis** [comment] 2021-12-04 13:46
This should be resolved in the 0.11 beta. Are you able to install it and test it out?

**Comment by jb123567** [comment] 2021-12-04 13:52
Already installed, will let you know if the error occurs again!

**Comment by AngellusMortis** [comment] 2021-12-18 13:28
It sounds like the issue is fixed since we have not heard back. I am going to close this for now and if you have any more issues, let us know!

**Closed by AngellusMortis** 2021-12-18 13:28 UTC
Labels: bug
