### ISSUE TITLE
Video delay

### ISSUE THREAD

**Issue by NVader2000** [briis/unifiprotect#199] opened 2021-02-23 11:40 UTC
I know that I have already posted about this issue, but I wanted to bring it back up for a couple of reason. One, the delay is still there but has improved. Before it was about 20-30 second delay, now it is about 7-10 seconds. However, I am not using RTSP. Is RTSP required? If so, how is my configuration working? I followed every step to the 't' except for the RTSP. Would using RTSP improve the delay? Would lower resolution RTSP also improve delay?

I am running a UDMP with 1.9.0-12 and Protect with 1.17.3

Please advise and thank you.

**Comment by briis** [comment] 2021-02-23 11:58
Hi,
Yes you can use the system without enabling RTSP, the downside is you are missing Audio - The upside is that you will get more realtime video. If I disable RTSP on a Camera, I only have a delay of around 2 seconds.

If you enable RTSP, you will see a bit bigger delay in the stream, and I assume it is due to HA has to process and decode the stream (Audio and Video), and that the extra seconds.

**Comment by NVader2000** [comment] 2021-02-23 12:08
AH, ok. Yes, not interested in audio. What FPS and Image Quality are you running your cameras at? Plus, video is choppy as well. On my Protect setup video is exceptionally smooth. What could I be missing?

**Comment by briis** [comment] 2021-02-24 07:56
I have currently only tested this on a G3 Flex Camera, which runs at 25 FPS and a bitrate of 6000 Kbps. This gives a smooth video with around 2 seconds delay. I also have an UDMP and my HA instance is running in Supervised mode on an Intel NUC i7, with 16GB Ram - and this is the only thing this NUC does.

**Comment by AngellusMortis** [comment] 2021-05-07 14:34
The delay is actually caused by HLS. It appears the Unifi cameras have a 5 second keyframe which cannot be changed so that means the HA must wait for a whole keyframe before it can make a HLS segment causing a minimum of a 5 second delay.

https://github.com/home-assistant/architecture/issues/113#issuecomment-460024458

**Comment by AngellusMortis** [comment] 2021-07-25 13:10
For anyone looking to get a lower delay, you can replace HLS with WebRTC/

https://github.com/briis/unifiprotect/issues/238

**Comment by briis** [comment] 2021-08-24 06:15
As stated in this issue there are some work-arounds to get a faster RTSP stream, but from this Integration there is not much we can do, before the internals of HA changes. So I will close this issue.

**Closed by briis** 2021-08-24 06:15 UTC
