### ISSUE TITLE
Delay between person detection and camera snapshot

### ISSUE THREAD

**Issue by gulli1986** [briis/unifiprotect#246] opened 2021-06-10 07:25 UTC
First things first, loving this integration, have been playing with it a lot lately.
I came across any issue when doing snapshot.

I made a simple automation that call the camera.snapshot service when the binary_sensor.motion_XXX report a person as an event object. This automation is working, however, there seems to be a 6-7 seconds delays between the trigger and the time the snapshot is taken which means I sometimes don't actually see the person on the snapshot as he/she have moved out of the camera field.

I have seen these issue on both a G4-bullet and a G4-doorbell. Is this just the way it is or is there a way to reduce the lag between the trigger and the time the snapshot is taken?

The cameras are running on a UDM PRO running latest firmware 1.9.3, Unifi Controller 6.2.25 and Unifi Protect 1.18.1.
Home Assistant is running on a HA Blue limited edition.

Cheers.

**Comment by briis** [comment] 2021-06-10 13:13
It is caused by the delay in the stream, that I unfortunately have not been able fix yet. So the motion sensor is instantly, but the stream lags a bit behind. I hope that one day the stream can be fixed but until then I have two suggestions:
1. Either try to put a delay in your automation, before you take the snapshot or
2. Disable the RTSP stream in the Configuration Menu of the integration, and see if that helps.

**Comment by gulli1986** [comment] 2021-06-10 13:23
Hello Bjarne @briis , thanks for your feedback.

I tried putting a delay before taking the snapshot however most of the time the person will have left the camera field of you before the snapshot is taken so this doesn't help.

On the other hand your proposed solution to disable the RTSP stream seems to help, it looks like the delay is reduced enough so that I get a snapshot with a person, thanks! :)

**Comment by briis** [comment] 2021-06-10 13:41
I really hope I can get this RTSP stream instantly one day - I am waiting for an update to the HA `stream` component.

Just note that disabling the RTSP stream, removes Audio, so hopefully you can live without that.

**Comment by gulli1986** [comment] 2021-06-10 13:49
I can live without the audio, at least for the G4-bullet. Would be nice to have the sound for the G4-doorbell but not a must. Reducing the stream delay is definitely the most important part for me to ensure good snapshots.

Let's hope the RTSP stream can be fixed one day!

**Comment by briis** [comment] 2021-06-21 17:54
I will close this now, and will fix the stream as soon as possible.

**Closed by briis** 2021-06-21 17:54 UTC

**Comment by gulli1986** [comment] 2021-06-23 10:29
No problem @briis.
Just for your information, I did some further testing without RTSP enabled and still experienced the same problem from time to time.

After some troubleshooting I found out that if you trigger on motion only and take a snapshot, the snapshot is taken instantaneously as the motion is detected. However if I trigger by using event object (person), it looks like the snapshot is taken at the end of the motion. Hence the reason why it was too late for me (the person gets outside of the camera view).

Using motion only did the trick for me. Any idea how I could still use the event object person and get the snapshot triggered as the person is first detected and not wait till the end of the detection?

**Comment by tonysurma** [comment] 2021-07-31 21:23
> No problem @briis.
> Just for your information, I did some further testing without RTSP enabled and still experienced the same problem from time to time.
> 
> After some troubleshooting I found out that if you trigger on motion only and take a snapshot, the snapshot is taken instantaneously as the motion is detected. However if I trigger by using event object (person), it looks like the snapshot is taken at the end of the motion. Hence the reason why it was too late for me (the person gets outside of the camera view).
> 
> Using motion only did the trick for me. Any idea how I could still use the event object person and get the snapshot triggered as the person is first detected and not wait till the end of the detection?

I am having the exact same thing today.  The only solution I found (which can be a bit of overhead) is to take a snapshot and store it in media on motion in a fixed file name (and I have a condition so it won't do this more than once a minute) and then in the action for the person detection I send that stored snapshot from the media file.

The overhead is that it will store a snaphot on every motion (but not more than once every 60 seconds) even if person detection doesn't come.

The 'inaccuracy' in this is it might not be the first motion trigger that shows a good shot of the person but it is better than a picture from after they have left for now

**Comment by gulli1986** [comment] 2021-08-01 17:56
> I am having the exact same thing today. The only solution I found (which can be a bit of overhead) is to take a snapshot and store it in media on motion in a fixed file name (and I have a condition so it won't do this more than once a minute) and then in the action for the person detection I send that stored snapshot from the media file.
> 
> The overhead is that it will store a snaphot on every motion (but not more than once every 60 seconds) even if person detection doesn't come.
> 
> The 'inaccuracy' in this is it might not be the first motion trigger that shows a good shot of the person but it is better than a picture from after they have left for now

I did some testing and I am pretty convinced the delay is not related to the delay in the RSTP stream but rather in the way the person detection works, i.e that the person detection does not trigger till after the motion is completed.

@briis is there something that can be looked at? Within the unifi protect app all person detection are spot on without any sort of delays so it may be something related to the integration?
