### ISSUE TITLE
Support UP-Sense

### ISSUE THREAD

**Issue by jonbloom** [briis/unifiprotect#202] opened 2021-03-04 00:16 UTC
Ubiquiti has released (in Early Access) a BT connected multisensor. Here's a link: https://store.ui.com/collections/early-access/products/unifi-protect-sense-beta

It would be pretty fantastic to get the sensor data into HA the same way cameras etc are available. Happy to help with whatever data I can provide from my Protect system to assist in supporting the sensor in HA.

**Comment by briis** [comment] 2021-03-04 07:43
Looks like a really cool product with tons of features and many use cases. I will need a the raw output of the bootstrap API to detect what is recorded for this device to start working on it. Unfortunately it is not even listed in the EU Early Access Store.

I will see if I can mock up a program you can run to dump the data I need.

**Comment by jonbloom** [comment] 2021-03-04 16:05
Sounds good. 

We'd love to have you in the [un-official] [Ubiquiti Discord](https://discord.io/ubiquiti), where we could get a bit of a real-time conversation going around this integration. You're very popular over there!

**Comment by briis** [comment] 2021-03-04 17:03
Hi,
I put a quick program together to enable you to get all the raw data from your Protect Instance. 

* If you have not already, please install Python on a machine (3.8 or higher)
* Download [this Python program](https://github.com/briis/pyunifiprotect/blob/master/protectdata.py) 
* Install the IO module that the Integration also uses: `pip3 install pyunifiprotect`
* Then run the program: `python3 protectdata.py > cameras.json` 

Then post that file (`cameras.json`) here, or send it to me, and I will see what the UP-Sense device stores in the API.

And thanks for the Discord invite, I will most certainly join (I did not know it existed)

**Comment by JacobErnst98** [comment] 2021-03-10 19:13
> Hi,
> I put a quick program together to enable you to get all the raw data from your Protect Instance.
> 
> * If you have not already, please install Python on a machine (3.8 or higher)
> * Download [this Python program](https://github.com/briis/pyunifiprotect/blob/master/protectdata.py)
> * Edit the file, and insert your local Protect username, password and IP address of your CloudKey or UDMP. (Same values you use in HA)
> * Install the IO module that the Integration also uses: `pip3 install pyunifiprotect`
> * Then run the program: `python3 protectdata.py > cameras.json`
> 
> Then post that file (`cameras.json`) here, or send it to me, and I will see what the UP-Sense device stores in the API.
> 
> And thanks for the Discord invite, I will most certainly join (I did not know it existed)

I sent data in an email to you, hope it helps!

**Comment by briis** [comment] 2021-03-11 07:09
Thanks Jacob,
Jon also send this to me, but good to have it from two instances.

This will require some work, as I need to create a whole new entity type for Sensors, and then track status for those. 

As I can't get my hands on this device, could you describe what it does, and maybe attach a few screenshots on how it looks in the APP? As I can read it there are several sensors attached, and just getting a description about:
- Which of them update on a time based frequency?
- Which of them update on an event (Door open/close)
- Any other info you can share.

**Comment by briis** [comment] 2021-03-11 08:12
Hi both,
The above program gave me info about the sensors and their state, but not about the events that are being pushed out. In order to capture those, I will need you to run [this python program](https://github.com/briis/pyunifiprotect/blob/master/websocket_test.py) and then capture the output in a file. This will capture all events for all attached devices, but I will then filter it later. 

When you run it, try and activate as many of the features like door open/close as you can, to ensure we capture it in the file.

Edit it first to supply username, password and IP address.

**Comment by briis** [comment] 2021-03-11 11:33
Hi both,
I have something to test for you. Just to ensure you know how this works (And you might do already) - All the communication with the UniFi API goes through the module `pyunifiprotect` and this module then sends the data in the right format to Home Assistant.
So the first thing - and the hard thing - is to get that piece to work. So all the initial testing and coding is done on this module - and it is very difficult to do when not having the HW.

Anyway, I have now done the very first rough implementation of the sensor, and I need you to test if we get some formatted data. In order to do this, please do the following:

* Download [this new test program](https://github.com/briis/pyunifiprotect/blob/sensor/protectdata_sensor.py) (Remember to add your username, password and IP)
* Go to a terminal, and upgrade pyunifiprotect by doing: `pip3 install --upgrade pyunifiprotect` This should install 0.30.0
* Now run the program you downloaded in line 1, and send me the output. (Just ignore the Unclosed client session error you get at the end) Hopefully you will see your sensors in the JSON output. If you get other errors, let me know.

**Comment by JacobErnst98** [comment] 2021-03-11 22:25
> * pip3 install --upgrade pyunifiprotect

Email sent

**Comment by JacobErnst98** [comment] 2021-03-11 22:29
> Hi both,
> The above program gave me info about the sensors and their state, but not about the events that are being pushed out. In order to capture those, I will need you to run [this python program](https://github.com/briis/pyunifiprotect/blob/master/websocket_test.py) and then capture the output in a file. This will capture all events for all attached devices, but I will then filter it later.
> 
> When you run it, try and activate as many of the features like door open/close as you can, to ensure we capture it in the file.
> 
> Edit it first to supply username, password and IP address.

I ran this for a few hours and no data was ever put into the .txt file
python .\websocket_test.py > websocket_test.txt

**Comment by briis** [comment] 2021-03-12 06:31
For the device data it seems to work, as you now get data like this:

```json
"604010d00006ed0387000788": {
  "event_start": null,
  "event_score": 0,
  "event_thumbnail": null,
  "event_heatmap": null,
  "event_on": false,
  "event_ring_on": false,
  "event_type": null,
  "event_length": 0,
  "event_object": [],
  "name": "Office Door",
  "type": "sensor",
  "model": "UFP-SENSE",
  "mac": "74ACB91E7861",
  "ip_address": "None",
  "firmware_version": "0.0.58",
  "up_since": "2021-03-04 11:12:58",
  "online": true,
  "light_value": null,
  "humidity_value": 43,
  "temperature_value": 20.7,
  "battery_status": 88,
  "alarm_enabled": false,
  "light_enabled": false,
  "motion_enabled": true,
  "temperature_enabled": true,
  "humidity_enabled": true,
  "led_enabled": true,
  "server_id": "74ACB9E61A7D",
  "last_motion": "2021-03-11 17:19:12",
  "last_openchange": "2021-03-11 15:57:36"
 }
```
Whether we have all the right data needs to be verified, but the structure seems to work, so it is easy to add more data.

For the events: I had these issues also, but I still get something put out on the terminal. Do you see anything in the terminal output? If yes, just let it run for a little while and then copy the output in to a file.
When you test, go and open/close the door with the sensor to capture both motion and open/close events. As far as I can see this should be the two types of events that this sensor puts out.

**Comment by JacobErnst98** [comment] 2021-03-12 13:13
> For the device data it seems to work, as you now get data like this:
> 
> ```json
> "604010d00006ed0387000788": {
>   "event_start": null,
>   "event_score": 0,
>   "event_thumbnail": null,
>   "event_heatmap": null,
>   "event_on": false,
>   "event_ring_on": false,
>   "event_type": null,
>   "event_length": 0,
>   "event_object": [],
>   "name": "Office Door",
>   "type": "sensor",
>   "model": "UFP-SENSE",
>   "mac": "74ACB91E7861",
>   "ip_address": "None",
>   "firmware_version": "0.0.58",
>   "up_since": "2021-03-04 11:12:58",
>   "online": true,
>   "light_value": null,
>   "humidity_value": 43,
>   "temperature_value": 20.7,
>   "battery_status": 88,
>   "alarm_enabled": false,
>   "light_enabled": false,
>   "motion_enabled": true,
>   "temperature_enabled": true,
>   "humidity_enabled": true,
>   "led_enabled": true,
>   "server_id": "74ACB9E61A7D",
>   "last_motion": "2021-03-11 17:19:12",
>   "last_openchange": "2021-03-11 15:57:36"
>  }
> ```
> 
> Whether we have all the right data needs to be verified, but the structure seems to work, so it is easy to add more data.
> 
> For the events:
> You do the following to capture data in a file if you run Mac or linux: (The first command will ensure everything that is outputted on your terminal is captured in the file)
> 
> ```shell
> /usr/bin/script ~/Desktop/protect.txt
> python3 websocket_test.py
> ```
> 
> But do you see anything in the terminal output? If not, let me know, then there is something wrong with the program, but it works for me.
> 
> When you test, go and open/close the door with the sensor to capture both motion and open/close events. As far as I can see this should be the two types of events that this sensor puts out.
> There is however also _alarm_ data, but I am not sure what that is? Is there anything in the Web APP that says how this works?

Alarm data seems to be if a smoke detector is going off.
I also see "Tamper detection" on the mobile app and not in the web UI.
Im on windows so most likely STDOUT from py is not being piped correctly, I will save a copy of the terminal history for you.

**Comment by briis** [comment] 2021-03-12 13:27
>Alarm data seems to be if a smoke detector is going off.
I also see "Tamper detection" on the mobile app and not in the web UI.

Is there a smoke detector in this sensor also? Or is this a separate product?
Please also try and do the Tampering, when you log the events. We might as well get it as complete as possible.

Looking forward to the data.

**Comment by JacobErnst98** [comment] 2021-03-12 13:33
> > Alarm data seems to be if a smoke detector is going off.
> > I also see "Tamper detection" on the mobile app and not in the web UI.
> 
> Is there a smoke detector in this sensor also? Or is this a separate product?
> Please also try and do the Tampering, when you log the events. We might as well get it as complete as possible.
> 
> Looking forward to the data.
Is there a smoke detector in this sensor also? Or is this a separate product?
- The UP-Sense has a microphone to listen to smoke detectors, I don't have any working smoke detectors at the moment......
Please also try and do the Tampering, when you log the events. We might as well get it as complete as possible.
- I cant get it to dismiss but I can try to hit the tamper switch during my testing.

**Comment by briis** [comment] 2021-03-21 09:35
Did any of you have time to collect some event data?

**Comment by jonbloom** [comment] 2021-03-22 13:49
Sorry for the delay, I'll be sure to get a sensor up and running this week.

**Comment by jonbloom** [comment] 2021-03-29 14:20
@briis I ran the script for a while and kindof beat up my sensor to try to get some varied readings. I wasn't getting any output that wasn't camera based.

**Comment by briis** [comment] 2021-03-29 15:23
OK. I will look at the program again, and see how can ensure you capture something. Stay tuned...

**Comment by michaeladam** [comment] 2021-06-28 04:40
@briis is there still efforts going on to integrate the sensor?

I finally got a U6 AP and was able to get the sensor adopted.  However, it the integration crashes now due to a key error in pyunifiprotect.  Seems like it tries to load as a light, but the sensor does not have a host IP (since its bluetooth)

`Logger: homeassistant.config_entries
Source: custom_components/unifiprotect/data.py:48
Integration: Unifi Protect (documentation, issues)
First occurred: 9:23:39 PM (1 occurrences)
Last logged: 9:23:39 PM

Error setting up entry LLAP UDM Pro for unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/unifiprotect/__init__.py", line 99, in async_setup_entry
    await protect_data.async_setup()
  File "/config/custom_components/unifiprotect/data.py", line 32, in async_setup
    await self.async_refresh()
  File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
    await self._protectserver.update(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 123, in update
    await self._get_device_list(not self.ws_connection)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 316, in _get_device_list
    self._process_sensors_json(json_response, server_id, include_events)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 380, in _process_sensors_json
    process_sensor(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_data.py", line 228, in process_sensor
    "ip_address": str(sensor["host"]),
KeyError: 'host'`

**Comment by briis** [comment] 2021-06-28 07:18
I would really love to get this in, the issue is I cannot get the HW here in Europe, which makes development extremely difficult. I will look in to the above, to see why this fails, besides the obvious that there is no IP address.

**Comment by michaeladam** [comment] 2021-06-29 00:01
I got the integration working again.  It found the UFP-Sense and it shows up, but doesn't seem to work properly (which is fine, better than everything breaking! ;) )

I went a little crazy and hacked the code live on my HA instance.  I changed the following:
Line 232 of unifi_data.py to `"ip_address": str(sensor["host"] if "host" in sensor else "0.0.0.0"),`
Line 142 of switch.py to `return (self._device_data["status_light"] is True) if "status_light" in self._device_data else True`

That stopped all the crashing.

**Comment by briis** [comment] 2021-06-29 07:23
Thanks for the feedback. I will incorporate this in the next release, to ensure it does not break your system.
From earlier posts, it seems that you get the device listed in HA, but there are no events being processed for the UFP-Sense. This will not be done, before I can get my hands on one.

**Comment by briis** [comment] 2021-06-29 07:52
I just released 0.8.9, which incorporates this fix. I made some of the code a bit different, so please let me know if this still causes issues.

**Comment by michaeladam** [comment] 2021-06-30 17:35
Thanks! I will give it a try. Is there any debugging I can add to the code to help you in anyway?

**Comment by briis** [comment] 2021-07-01 06:06
If you still get errors, turn on debugging for the integration by adding this to your `configuration.yaml`:

```yaml
logger:
  default: error
  logs:
    custom_components.unifiprotect: debug
````
Besides from that, I really need the HW Device, as catching the events is a *Trial and Error* thing, which is hard to do, through somebody else.

**Comment by AngellusMortis** [comment] 2021-11-03 17:07
I am going to close this issue in favor of https://github.com/briis/unifiprotect/issues/315.

@briis and I are both trying to get the Sense working the best we can, but the device is rather different then existing devices. The other issue has a lot more newer conversation going on so if you have any issues with getting your sense working, please move the conversation over to that issue.

**Closed by AngellusMortis** 2021-11-03 17:07 UTC
Labels: feature-request
