### ISSUE TITLE
Camera not updating

### ISSUE THREAD

**Issue by irgusite** [briis/unifiprotect#82] opened 2020-06-13 13:08 UTC
Hi, 

I use the unifi protect module on my Unifi Dream Machine Pro to record the camera stream.
I activated the rstp streams on the camera settings, but in home assistant I still have an image every 4-5 seconds. Did I miss something?

![image](https://user-images.githubusercontent.com/6170298/84569541-ad6ccb80-ad87-11ea-95bf-03907d1f35b4.png)

Edit:
UDM on fw 1.7.0
Home Assistant: 0.111.0
Integation: last version on hacs (don't find where the version is on the new hacs interface)

Thank you for your awesome integration :)

**Comment by briis** [comment] 2020-06-13 15:12
Hi @irgusite 
The above looks correct. Here is what is expected behaviour:

If you add a *Picture Entity* card to your Frontend, and then add on of your Cameras as Entity for the that, you should get a still image, that updates approximately every 10 seconds on the Frontend. If you click on the image it will open up a new Window where it will stream the Video directly (The first time you might need to close the Window and reopen it again). On that stream you will have a delay of 10-15 seconds from realtime, but that is not something I can do anything about as this relates to the stream component in Home Assistant.

So if you are referring to the 10 seconds only update on the Frontend - that is expected behaviour.

>If I misunderstood your question, please give me a bit more info on where you see the delay.

**Comment by irgusite** [comment] 2020-06-13 18:18
I'm talking about the feed it open when you click on it. 
This one is showing 1 image every 5-10 seconds approximately. So not as expected :)

**Comment by briis** [comment] 2020-06-14 05:22
Ok, could you go to *States* in the *Developer* tab and find one of your Cameras. Then under Attributes tell me the value of the attribute called `supported_features`

**Comment by irgusite** [comment] 2020-06-14 07:39
Yes it says supported_features: 2

**Comment by briis** [comment] 2020-06-14 07:45
That means that the Integration has read the RTSP stream and can stream. Unfortunately I have not seen this on any other installations, and cannot reproduce it. So the only other thing I can think of is that the HW you are running Home Assistant on is struggling?

If copy the rtsp stream command you show above, and open up f.ex VLC, is it then streaming fine?

**Comment by irgusite** [comment] 2020-06-14 08:05
The hardware is an Intel xeon processor with 8Gb of ram, and the motion eye
stream is working fine.
In VLC it is working fine.
I will continue to search, and test it on a clean instance to see :)

>

**Comment by briis** [comment] 2020-06-14 08:24
One more thing to try:
Is `stream:` added to your `configuration.yaml`? If not, try add that, and restart Home Assistant.
See more [here](https://www.home-assistant.io/integrations/stream/)

**Comment by irgusite** [comment] 2020-06-14 09:01
Oh, this was it. I overlooked this configuration ...

Thank you very much :)

**Comment by briis** [comment] 2020-06-14 09:05
Perfect, glad it works. Please close the Issue if all works.

**Closed** 2020-06-14 09:05 UTC
