### ISSUE TITLE
Binary Sensor Doorbell not triggered

### ISSUE THREAD

**Issue by BoisMaison** [briis/unifiprotect#341] opened 2021-11-19 18:06 UTC
### Home Assistant Version?

2021.10.6

### UniFi Protect Version?

1.19.2

### UniFi Protect HA Integration version?

0.9.1

### What happened?

When the doorbell is pressed, the binary sensor (doorbell) is not triggered, meaning it cannot be used in home assistant. All other triggers (motion detection) work flawless.

**Comment by AngellusMortis** [comment] 2021-11-19 18:24
I am not able to reproduce and I just got a package this morning. I am on the latest 0.10 beta, but that should not matter since the core entities have not been changed for 0.10.

![image](https://user-images.githubusercontent.com/490848/142672685-348e4c72-c1ba-464c-b873-8004e211332e.png)

There are binary sensors two sensors for cameras with a chime (like the G4 Doorbell). One is for motion and one is for the chime.

Make sure you are using the right one. You want to make sure you use the one with the doorbell icon, not the one with the walking icon.

![image](https://user-images.githubusercontent.com/490848/142672746-cceac644-a991-4577-b511-636dd8c1caff.png)

**Comment by briis** [comment] 2021-11-19 18:37
You could try and use the event that is also fired when the doorbell is pressed. See [this example](https://github.com/briis/unifiprotect#send-a-notification-when-the-doorbell-is-pressed) in the documentation.

@AngellusMortis I have seen this before for some users. It might be a timing issue. So maybe we should see if we could let the sensor be on for 2-3 seconds before reverting to off.

**Comment by BoisMaison** [comment] 2021-11-19 18:38
Maybe I had to try it before, but after a full reboot and reinstallation of the UniFi doorbell itself, it works like a charm now. Might be useful to for other who face this (still strange) issue.

**Comment by briis** [comment] 2021-11-19 18:40
All that shouldn't be necessary, but sometimes with Ubiquity HW and SW it just needs some love (and reboots)

**Comment by KasperHoldum** [comment] 2021-11-25 16:48
I experience the same thing. Most of the time the doorbell event is fired, but sometimes it is not. Which makes the doorbell unreliable.

**Comment by AngellusMortis** [comment] 2021-12-04 13:47
I added code to the 0.11 to handle this case better. Are able to install it and test it out?

**Comment by BoisMaison** [comment] 2021-12-05 19:59
So far the integration works flawless, I did not need another reset anymore.

**Comment by AngellusMortis** [comment] 2021-12-05 20:00
I am going to go ahead and close this one as confirms fixed in 0.11 then. Thanks for checking and replying.

**Closed by AngellusMortis** 2021-12-05 20:00 UTC
Labels: bug
